//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTraining
    {
        public int EmployeeTrainingId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> SkillsId { get; set; }
        public Nullable<int> TrainingId { get; set; }
        public Nullable<System.DateTime> AcquiredOn { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public bool Completed { get; set; }
        public Nullable<System.DateTime> CompletedTimestamp { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual Training Training { get; set; }
    }
}
