//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSMWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skill()
        {
            this.EmployeeTrainings = new HashSet<EmployeeTraining>();
        }
    
        public int SkillsId { get; set; }
        public string SkillsDescription { get; set; }
        public Nullable<int> PeriodicityId { get; set; }
        public string QMNumber { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> SkillStatus { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTraining> EmployeeTrainings { get; set; }
        public virtual Periodicity Periodicity { get; set; }
    }
}
